// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsX6hOZRkcAJN6fXj7qVk4cSDS844VKQg',
    appId: '1:924300751027:web:1a4d4546acd94dc4eb40c6',
    messagingSenderId: '924300751027',
    projectId: 'instagramclone-a0f76',
    authDomain: 'instagramclone-a0f76.firebaseapp.com',
    storageBucket: 'instagramclone-a0f76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByhQu_dbfOrUAbWLBHM0X8zMALcNB8rnw',
    appId: '1:924300751027:android:03693ce679ecf318eb40c6',
    messagingSenderId: '924300751027',
    projectId: 'instagramclone-a0f76',
    storageBucket: 'instagramclone-a0f76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB06-3lAaIoeIzeIqoKmZ419BHOj4f1Vz4',
    appId: '1:924300751027:ios:488e62d4018f8359eb40c6',
    messagingSenderId: '924300751027',
    projectId: 'instagramclone-a0f76',
    storageBucket: 'instagramclone-a0f76.appspot.com',
    iosClientId: '924300751027-s1of1m0680jt503rolopallc5e72afbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
